// Generated by CoffeeScript 1.10.0
(function() {
  var churn, execSync;

  execSync = require("child_process").execSync;

  churn = function(filePath) {
    var command, output;
    command = "git whatchanged " + filePath + " | grep 'commit' | wc -l";
    output = execSync(command);
    return parseInt(output, 10);
  };

  module.exports = churn;

}).call(this);
