// Generated by CoffeeScript 1.10.0
(function() {
  var CoffeeLint, complexityConfig, cyclomaticComplexity, divide, objectValueMax, objectValueTotal, ref;

  CoffeeLint = require("coffeelint");

  ref = require("../util"), divide = ref.divide, objectValueMax = ref.objectValueMax, objectValueTotal = ref.objectValueTotal;

  complexityConfig = {
    cyclomatic_complexity: {
      value: 0,
      level: "error"
    }
  };

  cyclomaticComplexity = function(file) {
    var output;
    output = CoffeeLint.lint(file, complexityConfig).reduce(function(hash, description) {
      var lineRange;
      if (description.rule === "cyclomatic_complexity") {
        lineRange = description.lineNumber + "-" + description.lineNumberEnd;
        hash.lines[lineRange] = description.context;
      }
      return hash;
    }, {
      lines: {}
    });
    output.total = objectValueTotal(output.lines);
    output.average = divide(output.total, Object.keys(output.lines).length);
    output.max = objectValueMax(output.lines);
    return output;
  };

  module.exports = cyclomaticComplexity;

}).call(this);
