// Generated by CoffeeScript 1.10.0
(function() {
  var CoffeeLint, complexityConfig, cyclomaticComplexity, divide;

  CoffeeLint = require("coffeelint");

  divide = require("../util").divide;

  complexityConfig = {
    cyclomatic_complexity: {
      value: 0,
      level: "error"
    }
  };

  cyclomaticComplexity = function(file) {
    var max, output, sum;
    sum = max = 0;
    output = CoffeeLint.lint(file, complexityConfig).reduce(function(hash, description) {
      var lineRange;
      if (description.rule === "cyclomatic_complexity") {
        lineRange = description.lineNumber + "-" + description.lineNumberEnd;
        hash.lines[lineRange] = description.context;
        sum += description.context;
        if (description.context > max) {
          max = description.context;
        }
      }
      return hash;
    }, {
      lines: {}
    });
    output.average = divide(sum, Object.keys(output.lines).length);
    output.max = max;
    output.total = sum;
    return output;
  };

  module.exports = cyclomaticComplexity;

}).call(this);
