// Generated by CoffeeScript 1.10.0
(function() {
  var CoffeeLint, divide, functionLength, functionLengthConfig, objectValueMax, objectValueTotal, ref;

  CoffeeLint = require("coffeelint");

  CoffeeLint.registerRule(require("coffeelint-no-long-functions"));

  ref = require("../util"), divide = ref.divide, objectValueMax = ref.objectValueMax, objectValueTotal = ref.objectValueTotal;

  functionLengthConfig = {
    no_long_functions: {
      value: 0,
      level: "error"
    }
  };

  functionLength = function(file) {
    var output;
    output = CoffeeLint.lint(file, functionLengthConfig).reduce(function(hash, description) {
      var lineRange;
      if (description.rule === "no_long_functions") {
        lineRange = description.lineNumber + "-" + description.lineNumberEnd;
        hash.lines[lineRange] = description.lineNumberEnd - description.lineNumber;
      }
      return hash;
    }, {
      lines: {}
    });
    output.total = objectValueTotal(output.lines);
    output.average = divide(output.total, Object.keys(output.lines).length);
    output.max = objectValueMax(output.lines);
    return output;
  };

  module.exports = functionLength;

}).call(this);
