// Generated by CoffeeScript 1.10.0
(function() {
  var CoffeeLint, divide, functionLength, functionLengthConfig;

  CoffeeLint = require("coffeelint");

  CoffeeLint.registerRule(require("coffeelint-no-long-functions"));

  divide = require("../util").divide;

  functionLengthConfig = {
    no_long_functions: {
      value: 0,
      level: "error"
    }
  };

  functionLength = function(file) {
    var max, output, sum;
    sum = max = 0;
    output = CoffeeLint.lint(file, functionLengthConfig).reduce(function(hash, description) {
      var length, lineRange;
      if (description.rule === "no_long_functions") {
        lineRange = description.lineNumber + "-" + description.lineNumberEnd;
        length = description.lineNumberEnd - description.lineNumber;
        hash.lines[lineRange] = length;
        sum += length;
        if (length > max) {
          max = length;
        }
      }
      return hash;
    }, {
      lines: {}
    });
    output.average = divide(sum, Object.keys(output.lines).length);
    output.max = max;
    return output;
  };

  module.exports = functionLength;

}).call(this);
