// Generated by CoffeeScript 1.10.0
(function() {
  var MAX_GPA, MIN_GPA, clamp, gpa, rawGpa, tokenComplexity;

  tokenComplexity = require("./token_complexity");

  clamp = require("../util").clamp;

  MIN_GPA = 0;

  MAX_GPA = 4;

  rawGpa = function(file, tokens) {
    var base, raw, tokenCount;
    tokenCount = tokens.length;
    if (!tokenCount) {
      return 0;
    }
    raw = tokenCount / tokenComplexity(tokens);
    return base = raw * MAX_GPA;
  };

  gpa = function(base, scorePenalties) {
    var penalized;
    penalized = base * scorePenalties.filePenalty * scorePenalties.functionPenalty * scorePenalties.complexityPenalty;
    return clamp(penalized, MIN_GPA, MAX_GPA);
  };

  module.exports = {
    rawGpa: rawGpa,
    gpa: gpa
  };

}).call(this);
