// Generated by CoffeeScript 1.10.0
(function() {
  var MAX_GPA, MIN_GPA, clamp, gpa, penalties;

  clamp = require("../util").clamp;

  penalties = require("../penalties");

  MIN_GPA = 0;

  MAX_GPA = 4;

  gpa = function(file, metrics) {
    var base, complexityPenalty, filePenalty, functionPenalty, penalized, raw, tokenComplexity, tokenCount;
    tokenCount = metrics.tokenCount, tokenComplexity = metrics.tokenComplexity;
    if (!tokenCount) {
      return 0;
    }
    raw = tokenCount / tokenComplexity;
    base = raw * MAX_GPA;
    filePenalty = penalties.longFile(tokenCount);
    functionPenalty = penalties.longFunction(metrics.functionLength.average);
    complexityPenalty = penalties.complexFile(metrics.cyclomaticComplexity.total);
    penalized = base * filePenalty * functionPenalty * complexityPenalty;
    return clamp(penalized, MIN_GPA, MAX_GPA);
  };

  module.exports = gpa;

}).call(this);
