// Generated by CoffeeScript 1.10.0
(function() {
  var letterGrade;

  letterGrade = function(numericGrade) {
    if ((0 <= numericGrade && numericGrade <= 0.8)) {
      return "F";
    } else if ((0.8 < numericGrade && numericGrade <= 1.6)) {
      return "D";
    } else if ((1.6 < numericGrade && numericGrade <= 2.4)) {
      return "C";
    } else if ((2.4 < numericGrade && numericGrade <= 3.2)) {
      return "B";
    } else if ((3.2 < numericGrade && numericGrade <= 4)) {
      return "A";
    }
  };

  module.exports = letterGrade;

}).call(this);
