// Generated by CoffeeScript 1.10.0
(function() {
  var rules, tokenComplexity;

  rules = require("../rules");

  tokenComplexity = function(tokens) {
    return tokens.reduce(function(sum, token) {
      var type;
      type = token[0];
      return sum += rules[type] || 0;
    }, 0);
  };

  module.exports = tokenComplexity;

}).call(this);
