// Generated by CoffeeScript 1.10.0
(function() {
  var analyze, churn, coffee, compile, cyclomaticComplexity, files, fs, functionLength, glob, gpa, letterGrade, nestedCoffeeScriptPattern, report, tokenComplexity, tokens, validFileSummary, version;

  version = require("../package.json").version;

  churn = require("./metrics/churn");

  tokenComplexity = require("./metrics/token_complexity");

  cyclomaticComplexity = require("./metrics/cyclomatic_complexity");

  functionLength = require("./metrics/function_length");

  letterGrade = require("./metrics/letter_grade");

  gpa = require("./metrics/gpa");

  coffee = require("coffee-script");

  tokens = coffee.tokens, compile = coffee.compile;

  fs = require("fs");

  glob = require("glob");

  nestedCoffeeScriptPattern = function(path) {
    return path + "/**/*\.+(coffee|coffee\.md|litcoffee)";
  };

  files = function(paths) {
    return paths.reduce(function(list, path) {
      var matchingFiles, stats;
      stats = fs.lstatSync(path);
      if (stats.isFile()) {
        list.push(path);
      } else if (stats.isDirectory()) {
        matchingFiles = glob.sync(nestedCoffeeScriptPattern(path));
        list = list.concat(matchingFiles);
      }
      return list;
    }, []);
  };

  analyze = function(filePath) {
    var e, error, file, summary;
    file = fs.readFileSync(filePath, "utf8");
    summary = {};
    try {
      compile(file);
      summary = validFileSummary(filePath, file);
    } catch (error) {
      e = error;
      summary.error = e.name + ": " + (e.stack.split("\n")[0]);
    }
    return summary;
  };

  validFileSummary = function(filePath, file) {
    var fileTokens, summary;
    fileTokens = tokens(file, {
      literate: coffee.helpers.isLiterate(filePath)
    });
    summary = {
      churn: churn(filePath),
      functionLength: functionLength(file),
      cyclomaticComplexity: cyclomaticComplexity(file),
      tokenComplexity: tokenComplexity(fileTokens),
      tokenCount: fileTokens.length
    };
    summary.gpa = gpa(file, summary);
    summary.letterGrade = letterGrade(summary.gpa);
    return summary;
  };

  report = function(filePaths, opts) {
    var scores;
    if (opts == null) {
      opts = {};
    }
    scores = files(filePaths).reduce(function(hash, file) {
      hash[file] = analyze(file);
      return hash;
    }, {});
    return JSON.stringify(scores, null, opts.indentSpace);
  };

  exports.clog = {
    report: report,
    analyze: analyze,
    VERSION: version
  };

}).call(this);
