// Generated by CoffeeScript 1.10.0
(function() {
  var complexFile, longFile, longFunction;

  complexFile = function(complexity) {
    if ((0 <= complexity && complexity <= 20)) {
      return 1;
    } else if ((20 < complexity && complexity <= 30)) {
      return 0.9;
    } else if ((30 < complexity && complexity <= 40)) {
      return 0.8;
    } else if (complexity > 40) {
      return 0.7;
    }
  };

  longFunction = function(averageFunctionLength) {
    if ((0 <= averageFunctionLength && averageFunctionLength <= 20)) {
      return 1;
    } else if ((20 < averageFunctionLength && averageFunctionLength <= 40)) {
      return 0.9;
    } else if ((40 < averageFunctionLength && averageFunctionLength <= 60)) {
      return 0.8;
    } else if (averageFunctionLength > 60) {
      return 0.7;
    }
  };

  longFile = function(tokens) {
    if ((0 <= tokens && tokens <= 1000)) {
      return 1;
    } else if ((1000 < tokens && tokens <= 2000)) {
      return 0.9;
    } else if ((2000 < tokens && tokens <= 4000)) {
      return 0.8;
    } else if (tokens > 4000) {
      return 0.7;
    }
  };

  module.exports = {
    complexFile: complexFile,
    longFile: longFile,
    longFunction: longFunction
  };

}).call(this);
