// Generated by CoffeeScript 1.10.0
(function() {
  var clamp, divide;

  clamp = function(number, min, max) {
    return Math.max(Math.min(max, number), min);
  };

  divide = function(numerator, denominator) {
    if (denominator) {
      return numerator / denominator;
    } else {
      return 0;
    }
  };

  module.exports = {
    clamp: clamp,
    divide: divide
  };

}).call(this);
